### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KeithAlt** [KeithAlt/go-crude-rest-api-example#6]
A personal TODO list for the project. Mainly the dev branch.

**Comment by KeithAlt** [comment]
- [ ] Flush out REST HTTP response renderers
- [ ] Flush out error handling & wrapping
- [ ] Rewrite tests such that failures don't leave the test product in the database 🤪
- [ ] Add timeout & retry to HTTP / database connection configs
